packer {
  required_version = ">= [[ .ubuntu23PackerMinVersion }}"
  required_plugins {
    proxmox = {
      source  = "{{ .pveProvider }}"
      version = ">= {{ .pveProviderVersion }}"
    }
  }
}

locals {
  packerstarttime = formatdate("YYYYMMDD", timestamp())
  vmdate = formatdate("YYMM", timestamp())
}

variable "password" {
  type = string
}

variable "username" {
  type = string
}

source "proxmox-iso" "autogenerated_1" {
  boot                    = "order=virtio0;ide2;net0"
  boot_command            = ["<esc><esc><esc><esc>e<wait>", "linux /casper/vmlinuz autoinstall ds=nocloud quiet ---<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>", "<enter><f10><wait>"]
  boot_wait               = "3s"
  cloud_init              = "false"
  cloud_init_storage_pool = "v3700"
  cores                   = {{ .cpu }}
  cpu_type                = "host"
  disks {
    disk_size         = "15G"
    format            = "raw"
    storage_pool      = "v3700"
    type              = "virtio"
  }

  additional_iso_files {
    cd_files = ["./meta-data", "./user-data"]
    cd_label = "cidata"
    unmount = true
    iso_storage_pool = "local"
  }

  insecure_skip_tls_verify = true
  iso_checksum             = "c7cda48494a6d7d9665964388a3fc9c824b3bef0c9ea3818a1be982bc80d346b"
  iso_storage_pool         = "datastore"
  iso_url                  = "https://releases.ubuntu.com/lunar/ubuntu-23.04-live-server-amd64.iso"
  memory                   = {{ .ram }}

  network_adapters {
    bridge = "vmbr101"
    model  = "virtio"
  }

  node                 = "sthings-pve1"
  os                   = "l26"
  password             = var.password
  pool                 = "packer"
  proxmox_url          = "https://sthings-pve1.labul.sva.de:8006/api2/json"
  ssh_password         = "ubuntu"
  ssh_timeout          = "20m"
  ssh_username         = "ubuntu"
  template_description = "Packer VM Template\n---\nSpecs  \nOS: ubuntu23  \nBuild Date: ${local.packerstarttime}\n---\nProvisioning \nUser: packer  \nPassword: Pac7er\n---\nMaintainer  \nPatrick Hermann patrick.hermann@sva.de  \nChristian Mueller christian.mueller@sva.de  \nMartin Wolf martin.wolf@sva.de\n---"
  template_name        = "ubuntu23-eva"
  unmount_iso          = true
  username             = var.username
}

build {
  sources = ["source.proxmox-iso.autogenerated_1"]

  provisioner "shell" {
    inline = ["sudo rm -rf /var/cache/apt/*.bin; sudo apt-get -y update; sudo apt-get -y upgrade; sudo apt-get -y install python3 cloud-init; sudo apt-get autoremove --purge -y && sudo apt-get autoclean -y && sudo apt-get clean -y; sudo rm -rf /var/lib/cloud/seed/nocloud.net; echo 'datasource_list: [ NoCloud, ConfigDrive ]' | sudo tee -a /etc/cloud/cloud.cfg.d/99_pve.cfg > /dev/null; sudo truncate -s 0 /etc/machine-id && echo 'machine-id was reset successfully'; sudo systemctl stop systemd-resolved; sudo sed -i 's/#DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf; sudo rm /etc/resolv.conf; sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf; sudo systemctl start systemd-resolved"]
  }

}
