packer {
  required_version = ">= [[ .rocky9PackerMinVersion ]]"
  required_plugins {
    proxmox = {
      source  = "[[ .pveProvider ]]"
      version = ">= [[ .pveProviderVersion ]]"
    }
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
  }
}

source "proxmox-iso" "autogenerated_1" {
  boot                    = "order=scsi0;ide2;net0"
  boot_command            = ["<tab> inst.ks=cdrom:sr1:/user-data<enter><wait>"]
  boot_wait               = "5s"
  cloud_init              = "false"
  cloud_init_storage_pool = "[[ .storagePool ]]"
  cores                   = [[ .cpu ]]
  cpu_type                = "host"
  scsi_controller         = "virtio-scsi-single"

  disks {
    disk_size         = "[[ .diskSize ]]G"
    format            = "raw"
    storage_pool      = "[[ .storagePool ]]"
    type              = "scsi"
  }

  additional_iso_files {
    cd_files = ["[[ .packerConfigMountPath ]]/meta-data", "[[ .packerConfigMountPath ]]/user-data"]
    cd_label = "cidata"
    unmount = true
    iso_storage_pool = "local"
  }

  insecure_skip_tls_verify = true
  iso_checksum             = "[[ .rocky9IsoChecksum ]]"
  iso_storage_pool         = "[[ .isoStoragePool ]]"
  iso_url                  = "[[ .rocky9IsoUrl ]]"
  memory                   = [[ .ram ]]

  network_adapters {
    bridge = "[[ .networkAdapdater ]]"
    model  = "virtio"
  }

  node                 = "[[ .node ]]"
  os                   = "l26"
  username             = var.username
  password             = var.password
  pool                 = "[[ .pool ]]"
  proxmox_url          = "[[ .proxmoxUrl ]]"
  ssh_username         = "[[ .rocky9User ]]"
  ssh_password         = "[[ .rocky9Password ]]"
  ssh_timeout          = "[[ .sshTimeout ]]"
  template_description = "Packer VM Template\n---\nSpecs  \nOS: rocky9  \nBuild Date: ${local.packerstarttime}\n---\nProvisioning \nMaintainer  \nPatrick Hermann patrick.hermann@sva.de \nChristian Mueller christian.mueller@sva.de \nMartin Wolf martin.wolf@sva.de\n---"
  template_name        = "[[ .vmTemplateName ]]"
  unmount_iso          = true
}

build {
  sources = ["source.proxmox-iso.autogenerated_1"]

  provisioner "shell" {
    inline = ["dnf update -y; dnf install -y python3-dnf cloud-utils-growpart; dnf install -y gdisk python3; shred -u /etc/ssh/*_key /etc/ssh/*_key.pub; rm -f /var/run/utmp; >/var/log/lastlog; >/var/log/wtmp; >/var/log/btmp; rm -rf /tmp/* /var/tmp/*; unset HISTFILE; rm -rf /home/*/.*history /root/.*history; rm -f /root/*ks; passwd -d root; passwd -l root; rm -f /etc/resolv.conf; ln -sf /run/NetworkManager/resolv.conf /etc/resolv.conf; echo manage_PasswordAuthentication ;sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config; sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config"]
  }

  provisioner "ansible" {
    ansible_env_vars       = ["ANSIBLE_REMOTE_TEMP=/tmp", "ANSIBLE_HOST_KEY_CHECKING=False", "ANSIBLE_SSH_ARGS=-oForwardAgent=yes -oControlMaster=auto -oControlPersist=60s -oHostKeyAlgorithms=+ssh-rsa   -oPubkeyAcceptedKeyTypes=+ssh-rsa", "ANSIBLE_NOCOLOR=True"]
    extra_arguments        = ["--scp-extra-args", "'-O'", "-e ansible_ssh_pass=[[ .rocky9Password ]]"]
    keep_inventory_file    = "true"
    playbook_file          = "[[ .ansiblePlayMountPath ]]/[[ .ansibleOsProvioning ]].yaml"
    user                   = "[[ .rocky9User ]]"
    galaxy_file            = "[[ .ansiblePlayMountPath ]]/requirements.yaml"
    galaxy_force_install   = "true"
  }

}

locals {
  packerstarttime = formatdate("YYYY-MM-DD", timestamp())
  vmdate = formatdate("YYMM", timestamp())
}

variable "password" {
  type = string
}

variable "username" {
  type = string
}