packer {
  required_version = ">= [[ .ubuntu23PackerMinVersion ]]"
  required_plugins {
    proxmox = {
      source  = "[[ .pveProvider ]]"
      version = ">= [[ .pveProviderVersion ]]"
    }
    ansible = {
      source  = "[[ .ansibleProvisioner ]]"
      version = ">= [[ .ansibleProvisionerMinVersion ]]"
    }
  }
}

source "proxmox-iso" "autogenerated_1" {
  boot                    = "order=virtio0;ide2;net0"
  boot_command            = ["<esc><esc><esc><esc>e<wait>", "linux /casper/vmlinuz autoinstall ds=nocloud quiet ---<enter><wait>", "initrd /casper/initrd<enter><wait>", "boot<enter>", "<enter><f10><wait>"]
  boot_wait               = "3s"
  cloud_init              = "false"
  cloud_init_storage_pool = "[[ .storagePool ]]"
  cores                   = [[ .cpu ]]
  cpu_type                = "host"
  disks {
    disk_size         = "[[ .diskSize ]]G"
    format            = "raw"
    storage_pool      = "[[ .storagePool ]]"
    type              = "virtio"
  }

  additional_iso_files {
    cd_files = ["[[ .packerConfigMountPath ]]/meta-data", "[[ .packerConfigMountPath ]]/user-data"]
    cd_label = "cidata"
    unmount = true
    iso_storage_pool = "local"
  }

  insecure_skip_tls_verify = true
  iso_url                  = "[[ .ubuntu22IsoUrl ]]"
  iso_checksum             = "[[ .ubuntu22IsoChecksum ]]"
  iso_storage_pool         = "[[ .isoStoragePool ]]"
  memory                   = [[ .ram ]]

  network_adapters {
    bridge = "[[ .networkAdapdater ]]"
    model  = "virtio"
  }

  node                 = "[[ .node ]]"
  os                   = "l26"
  username             = var.username
  password             = var.password
  pool                 = "[[ .pool ]]"
  proxmox_url          = "[[ .proxmoxUrl ]]"
  ssh_username         = "[[ .ubuntu22User ]]"
  ssh_password         = "[[ .ubuntu22Password ]]"
  ssh_timeout          = "[[ .sshTimeout ]]"
  template_description = "Packer VM Template\n---\nSpecs  \nOS: ubuntu22  \nBuild Date: ${local.packerstarttime}\n---\nProvisioning \nMaintainer  \nPatrick Hermann patrick.hermann@sva.de \nChristian Mueller christian.mueller@sva.de \nMartin Wolf martin.wolf@sva.de\n---"
  template_name        = "[[ .vmTemplateName ]]"
  unmount_iso          = true
}

build {
  sources = ["source.proxmox-iso.autogenerated_1"]

  provisioner "shell" {
    inline = ["sudo rm -rf /var/cache/apt/*.bin; sudo apt-get -y update; sudo apt-get -y upgrade; sudo apt-get -y install python3 cloud-init; sudo apt-get autoremove --purge -y && sudo apt-get autoclean -y && sudo apt-get clean -y; sudo rm -rf /var/lib/cloud/seed/nocloud.net; echo 'datasource_list: [ NoCloud, ConfigDrive ]' | sudo tee -a /etc/cloud/cloud.cfg.d/99_pve.cfg > /dev/null; sudo truncate -s 0 /etc/machine-id && echo 'machine-id was reset successfully'; sudo systemctl stop systemd-resolved; sudo sed -i 's/#DNSStubListener=yes/DNSStubListener=no/g' /etc/systemd/resolved.conf; sudo rm /etc/resolv.conf; sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf; sudo systemctl start systemd-resolved"]
  }

  provisioner "ansible" {
    ansible_env_vars       = ["ANSIBLE_REMOTE_TEMP=/tmp", "ANSIBLE_HOST_KEY_CHECKING=False", "ANSIBLE_SSH_ARGS=-oForwardAgent=yes -oControlMaster=auto -oControlPersist=60s -oHostKeyAlgorithms=+ssh-rsa   -oPubkeyAcceptedKeyTypes=+ssh-rsa", "ANSIBLE_NOCOLOR=True"]
    extra_arguments        = ["--scp-extra-args", "'-O'"]
    keep_inventory_file    = "true"
    playbook_file          = "[[ .ansiblePlayMountPath ]]/[[ .ansibleOsProvisioning ]].yaml"
    user                   = "[[ .ubuntu23User ]]"
  }

}

locals {
  packerstarttime = formatdate("YYYY-MM-DD", timestamp())
  vmdate = formatdate("YYMM", timestamp())
}

variable "password" {
  type = string
}

variable "username" {
  type = string
}